export const colors = {
  light: {
    background: '#f3f4f6',
    card: '#ffffff',
    text: '#1f2937',
    textSecondary: '#6b7280',
    textTertiary: '#9ca3af',
    border: '#e5e7eb',
    primary: '#3b82f6',
    primaryLight: '#eff6ff',
    success: '#10b981',
    successLight: '#d1fae5',
    warning: '#f59e0b',
    warningLight: '#fef3c7',
    danger: '#ef4444',
    dangerLight: '#fee2e2',
    purple: '#8b5cf6',
    purpleLight: '#ede9fe',
    orange: '#f97316',
    orangeLight: '#ffedd5',
    navBackground: '#ffffff',
    navBorder: '#e5e7eb',
    elevation: {
      sm: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
      },
      md: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      lg: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 4,
      },
    },
  },
  dark: {
    background: '#000000',
    card: '#1C1C1E',
    text: '#FFFFFF',
    textSecondary: '#EBEBF5',
    textTertiary: '#8E8E93',
    border: '#38383A',
    primary: '#60a5fa',
    primaryLight: '#1A2D4A',
    success: '#34d399',
    successLight: '#0D3B2A',
    warning: '#fbbf24',
    warningLight: '#3B2E0A',
    danger: '#f87171',
    dangerLight: '#5C1A1A',
    purple: '#a78bfa',
    purpleLight: '#2D1B4E',
    orange: '#fb923c',
    orangeLight: '#3D2108',
    navBackground: '#1C1C1E',
    navBorder: '#38383A',
    elevation: {
      sm: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.4,
        shadowRadius: 2,
        elevation: 1,
      },
      md: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 2,
      },
      lg: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
        elevation: 4,
      },
    },
  },
};

export const getColors = (isDark) => {
  return isDark ? colors.dark : colors.light;
};
