export const colors = {
  light: {
    background: '#f3f4f6',
    card: '#ffffff',
    text: '#1f2937',
    textSecondary: '#6b7280',
    textTertiary: '#9ca3af',
    border: '#e5e7eb',
    primary: '#3b82f6',
    primaryLight: '#eff6ff',
    success: '#10b981',
    successLight: '#d1fae5',
    warning: '#f59e0b',
    warningLight: '#fef3c7',
    danger: '#ef4444',
    dangerLight: '#fee2e2',
    purple: '#8b5cf6',
    purpleLight: '#ede9fe',
    orange: '#f97316',
    orangeLight: '#ffedd5',
    navBackground: '#ffffff',
    navBorder: '#e5e7eb',
    elevation: {
      sm: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
      },
      md: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      lg: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 4,
      },
    },
  },
  dark: {
    background: '#111827',
    card: '#1f2937',
    text: '#f3f4f6',
    textSecondary: '#d1d5db',
    textTertiary: '#9ca3af',
    border: '#374151',
    primary: '#60a5fa',
    primaryLight: '#1e3a5f',
    success: '#34d399',
    successLight: '#064e3b',
    warning: '#fbbf24',
    warningLight: '#451a03',
    danger: '#f87171',
    dangerLight: '#7f1d1d',
    purple: '#a78bfa',
    purpleLight: '#3b0764',
    orange: '#fb923c',
    orangeLight: '#431407',
    navBackground: '#1f2937',
    navBorder: '#374151',
    elevation: {
      sm: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 1,
      },
      md: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 2,
      },
      lg: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 4,
      },
    },
  },
};

export const getColors = (isDark) => {
  return isDark ? colors.dark : colors.light;
};
